## Machine Learning With Python: Save And Load Trained Model

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [3]:
df=pd.read_csv('homeprices.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[6000]])

C:\Users\admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([995342.46575342])

### Save Model To a File Using Python Pickle

In [8]:
import pickle


In [9]:
with open('model_pickle','wb') as file:    #wb:binary data
    pickle.dump(model,file)

In [ ]:
#Load Saved Model

In [10]:
with open('model_pickle','rb') as file:      #rb:read binary data
    mp=pickle.load(file)                 #the file loaded with in mp object or model

In [11]:
mp.coef_

array([135.78767123])

In [12]:
mp.intercept_

180616.43835616432

In [13]:
mp.predict([[6000]])

C:\Users\admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([995342.46575342])

## Save Trained Model Using joblib

In [15]:
!pip install joblib

In [17]:
from sklearn.externals import joblib


ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\admin\anaconda3\lib\site-packages\sklearn\externals\__init__.py)